# 12_letters_content_patch.yaml
# Expands Letters with ready-to-adapt drafts and concise disclaimers.
pages:
  - title: "Letter – Credit Card Company (Notification of Death)"
    icon: "emoji:✉️"
    Body: |
      Re: Account {{Last 4 digits}} — Notification of Death
      
      To whom it may concern,
      
      I am writing to notify you of the death of {{Decedent Full Name}}, who held the above account. I am the appointed executor and request that the account be noted accordingly. Please provide the process for closing the account and the list of any required documents.
      
      Attached/Available on request:
      • Copy of death certificate
      • Proof of executor appointment
      
      Please direct future correspondence to:
      {{Executor Name}}
      {{Executor Address}}
      {{Executor Phone}} • {{Executor Email}}
      
      Thank you for your assistance.
      
      Sincerely,
      {{Executor Name}}
    Disclaimer: "This is a general sample. Requirements vary by issuer. Confirm instructions before sending."
  - title: "Letter – Bank (Account Transition/Closure)"
    icon: "emoji:✉️"
    Body: |
      Re: {{Bank Name}} — {{Account Type}} — {{Last 4 digits}}
      
      Dear {{Bank Name}} Estate Services,
      
      I am notifying you of the death of {{Decedent Full Name}} and request guidance to transition or close the referenced account. I am the executor for the estate. Please provide required forms and next steps.
      
      Included/Available:
      • Death certificate
      • Executor appointment
      • Government-issued ID
      
      Please confirm receipt and the expected timeline.
      
      Sincerely,
      {{Executor Name}} — Executor
    Disclaimer: "General sample; verify bank-specific estate procedures."
  - title: "Letter – Utility Provider (Service Change/Closure)"
    icon: "emoji:✉️"
    Body: |
      Re: Service at {{Service Address}} — Account {{Account Number}}
      
      Hello,
      
      I’m writing to notify you of the death of {{Decedent Full Name}}. Please advise on closing or transferring this service and any final bill requirements.
      
      Contact for this account:
      {{Executor Name}} — Executor
      {{Executor Phone}} • {{Executor Email}}
      
      Thank you.
    Disclaimer: "Confirm utility’s policy; some allow transfer with minimal documentation."
